version: '3'

services:
    web:
        restart: always
        build: ./web/
        expose:
            - "8123"
        volumes:
            - ./web:/code
        command:  python3 manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"

    nginx:
        restart: always
        build: ./nginx/
        ports:
            - "8765:80"
        volumes:
            - ./web/GenSci/static:/var/www/static
            - ./config/gensci.conf:/etc/nginx/conf.d
        depends_on:
            - web
